import React, { useState, useEffect, useRef } from 'react';
import api from '../../config/api';
import { notifyUpdate } from '../../utils/sync';
import { Save, Search, Trash2, X, AlertCircle, CheckCircle, Download, KeyRound, Bell, RefreshCw, XCircle } from 'lucide-react';
import * as XLSX from 'xlsx';
import { Button } from '../../components/ui/Button';
import { Input, Label, FormField } from '../../components/ui/Input';
import { Card, CardHeader, CardTitle, CardContent } from '../../components/ui/Card';
import { useUi } from '../../context/UiContext';

const clientNormalizeEmailPart = (str) => {
    if (!str) return '';
    const firstWord = str.trim().split(/\s+/)[0];
    return firstWord
        .normalize('NFD')
        .replace(/\p{Mn}/gu, '')
        .toLowerCase()
        .replace(/[^a-z0-9]/g, '');
};

const ClientsPage = () => {
    const { toast } = useUi();
    const [loading, setLoading] = useState(false);
    const [isEditing, setIsEditing] = useState(false);
    const [emailManuallySet, setEmailManuallySet] = useState(false);
    const [bulkUpdating, setBulkUpdating] = useState(false);
    const [clients, setClients] = useState([]); // For export purposes

    // Search State
    const [searchCedula, setSearchCedula] = useState('');
    const [isSearching, setIsSearching] = useState(false);

    // Initial Form State
    const initialFormState = {
        id: '', // Database Primary Key
        customerId: '', // Business Key (Will be auto-generated by backend if empty)
        cedula: '',
        name: '',
        surname1: '',
        surname2: '',
        email: '',
        password: '123', // Default
        genero: 'M',
        pais: 'Colombia',
        ciudad: '',
        tipoCliente: 'Final',
        socioFundador: 'SI',
        referido: '',
        cargo: '',
        fechaIngreso: new Date().toISOString().split('T')[0],
        fechaBaja: '',
        estatus: 'Activo'
    };

    const [formData, setFormData] = useState(initialFormState);

    const fetchClients = async () => {
        try {
            const res = await api.get('/admin/clients');
            setClients(res.data);
        } catch (error) {
            console.error("Error fetching clients for export:", error);
        }
    };

    useEffect(() => {
        fetchClients();
    }, []);

    // --- Actions ---

    const handleSearch = async (e) => {
        e.preventDefault();
        if (!searchCedula.trim()) {
            toast.error('Ingrese una cédula para buscar.');
            return;
        }

        setIsSearching(true);
        try {
            // GET /clients/cedula/:cedula
            const res = await api.get(`/admin/clients/cedula/${searchCedula}`);
            const client = res.data;

            // Populate form with existing data
            setFormData({
                ...client,
                password: '', // Don't show hash
                surname1: client.surname1 || '',
                surname2: client.surname2 || '',
                referido: client.referido || '',
                cargo: client.cargo || '',
                ciudad: client.ciudad || '',
                fechaBaja: client.fechaBaja || ''
            });
            setIsEditing(true);
            toast.success('Socio encontrado. Modo edición activado.');
        } catch (error) {
            console.error("Search error:", error);
            if (error.response && error.response.status === 404) {
                toast.error('Socio no encontrado. Verifique la cédula.');
            } else {
                toast.error('Error en la búsqueda: ' + (error.message));
            }
            handleReset(); // Clean slate on error
        } finally {
            setIsSearching(false);
        }
    };

    const handleReset = () => {
        setFormData(initialFormState);
        setIsEditing(false);
        setSearchCedula('');
        setEmailManuallySet(false);
    };

    const handleSubmit = async (e) => {
        e.preventDefault();

        // Basic Frontend Validation
        if (!formData.cedula) return toast.error('La Cédula es obligatoria.');
        if (!formData.name) return toast.error('El Nombre es obligatorio.');
        if (!formData.surname1) return toast.error('El Primer Apellido es obligatorio.');

        setLoading(true);
        try {
            if (isEditing) {
                // UPDATE (PUT)
                await api.put(`/admin/clients/${formData.id}`, formData);
                toast.success('Socio actualizado exitosamente.');
            } else {
                // CREATE (POST)
                const res = await api.post('/admin/clients', formData);
                toast.success('Socio registrado exitosamente.');
                // A07: si el backend generó una contraseña temporal, mostrarla
                // UNA SOLA VEZ al admin para que se la comunique al socio.
                if (res.data?.tempPassword) {
                    window.alert(
                        `Socio creado.\n\nContraseña temporal: ${res.data.tempPassword}\n\n` +
                        `Anote este valor y entréguelo al socio.\nEl socio deberá cambiarla en su primer ingreso.`
                    );
                }
            }
            notifyUpdate('clients');
            handleReset();
        } catch (error) {
            console.error("Error saving client:", error);
            const msg = error.response?.data?.error || error.message;
            toast.error(`Error: ${msg}`);
        } finally {
            setLoading(false);
        }
    };

    const handleExport = () => {
        if (clients.length === 0) {
            toast.error('No hay datos para exportar.');
            return;
        }
        const dataToExport = clients.map(c => ({
            'Customer_id': c.customerId ?? '',
            'Nombre': c.name ?? '',
            '1 Apellido': c.surname1 ?? '',
            '2 Apellido': c.surname2 ?? '',
            'Estado': c.estatus ?? '',
            'Genero': c.genero ?? '',
            'Pais': c.pais ?? '',
            'Ciudad': c.ciudad ?? '',
            'Tipo de Cliente': c.tipoCliente ?? '',
            'Concatenar': [c.name, c.surname1, c.surname2].filter(Boolean).join(' '),
            'Socio Fundador': c.socioFundador ?? '',
            'Referido': c.referido ?? '',
            'Cargo': c.cargo ?? '',
            'Fecha de Ingreso': c.fechaIngreso ?? '',
            'Fecha de baja': c.fechaBaja ?? '',
            'Cedula': c.cedula ?? '',
            'Correo': c.email ?? '',
        }));

        const worksheet = XLSX.utils.json_to_sheet(dataToExport);
        const workbook = XLSX.utils.book_new();
        XLSX.utils.book_append_sheet(workbook, worksheet, 'Socios');
        XLSX.writeFile(workbook, 'Tabla_Clientes.xlsx');
        toast.success('Reporte de Socios descargado: Tabla_Clientes.xlsx');
    };

    const handleBulkUpdateEmails = async () => {
        if (!window.confirm('¿Actualizar los correos de TODOS los socios al formato nombre.apellido@credifuturo.com?\nEsta acción sobreescribirá los correos actuales.')) return;
        setBulkUpdating(true);
        try {
            const res = await api.post('/admin/clients/bulk-update-emails');
            toast.success(res.data.message || 'Correos actualizados.');
            fetchClients();
        } catch (error) {
            toast.error('Error: ' + (error.response?.data?.error || error.message));
        } finally {
            setBulkUpdating(false);
        }
    };

    // ── Solicitudes de recuperación de contraseña ─────────────────────────
    const [resetRequests, setResetRequests] = useState([]);
    const [showDropdown, setShowDropdown] = useState(false);
    const [loadingRequests, setLoadingRequests] = useState(false);
    const dropdownRef = useRef(null);

    const fetchResetRequests = async () => {
        setLoadingRequests(true);
        try {
            const res = await api.get('/admin/password-reset-requests?status=pending');
            setResetRequests(res.data.data || []);
        } catch {
            toast.error('Error al cargar solicitudes de contraseña.');
        } finally {
            setLoadingRequests(false);
        }
    };

    useEffect(() => {
        fetchResetRequests();
    }, []);

    useEffect(() => {
        const handleClickOutside = (e) => {
            if (dropdownRef.current && !dropdownRef.current.contains(e.target)) {
                setShowDropdown(false);
            }
        };
        if (showDropdown) document.addEventListener('mousedown', handleClickOutside);
        return () => document.removeEventListener('mousedown', handleClickOutside);
    }, [showDropdown]);

    // Auto-fill email cuando se escribe nombre/apellido en modo creación
    useEffect(() => {
        if (isEditing || emailManuallySet) return;
        const first = clientNormalizeEmailPart(formData.name);
        const last  = clientNormalizeEmailPart(formData.surname1);
        if (first || last) {
            setFormData(prev => ({ ...prev, email: `${first}.${last}@credifuturo.com` }));
        }
    }, [formData.name, formData.surname1, isEditing, emailManuallySet]);

    const pendingCount = resetRequests.filter(r => r.status === 'pending').length;

    const handleResetPassword = async () => {
        if (!formData.id) return;
        const nombre = `${formData.name} ${formData.surname1 || ''}`.trim();
        if (!window.confirm(`¿Restablecer contraseña de "${nombre}" a la contraseña genérica Coop2025?\n\nEl socio deberá cambiarla en su próximo ingreso.`)) return;
        setLoading(true);
        try {
            await api.post(`/admin/clients/${formData.id}/reset-password`, {});
            toast.success('Contraseña restablecida a Coop2025. El socio deberá cambiarla al ingresar.');
            fetchResetRequests();
        } catch (error) {
            toast.error('Error al resetear contraseña: ' + (error.response?.data?.error || error.message));
        } finally {
            setLoading(false);
        }
    };

    const handleResolveRequest = async (clientId, nombre) => {
        if (!window.confirm(`¿Restablecer contraseña de "${nombre}" a la contraseña genérica Coop2025?\n\nEl socio deberá cambiarla en su próximo ingreso.`)) return;
        try {
            await api.post(`/admin/clients/${clientId}/reset-password`, {});
            toast.success(`Contraseña restablecida a Coop2025. El socio deberá cambiarla al ingresar.`);
            setShowDropdown(false);
            fetchResetRequests();
        } catch (error) {
            toast.error('Error: ' + (error.response?.data?.error || error.message));
        }
    };

    const handleRejectRequest = async (requestId, nombre) => {
        if (!window.confirm(`¿Rechazar la solicitud de "${nombre}"?`)) return;
        try {
            await api.put(`/admin/password-reset-requests/${requestId}/reject`);
            toast.success('Solicitud rechazada.');
            setShowDropdown(false);
            fetchResetRequests();
        } catch (error) {
            toast.error('Error: ' + (error.response?.data?.error || error.message));
        }
    };

    const handleDelete = async () => {
        if (!formData.id) return;

        if (window.confirm(`¿Está seguro de eliminar al socio ${formData.name} ${formData.surname1}? Esta acción no se puede deshacer.`)) {
            setLoading(true);
            try {
                await api.delete(`/admin/clients/${formData.id}`);
                toast.success('Socio eliminado correctamente.');
                notifyUpdate('clients');
                handleReset();
                fetchClients(); // Refresh list
            } catch (error) {
                console.error("Delete error:", error);
                toast.error('Error al eliminar: ' + (error.message));
            } finally {
                setLoading(false);
            }
        }
    };

    return (
        <div className="max-w-4xl mx-auto space-y-6">

            {/* Header Area */}
            <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4 border-b border-gray-200 pb-4">
                <div>
                    <h1 className="text-2xl font-bold text-brand-dark">
                        {isEditing ? 'Editar Socio' : 'Registrar Nuevo Socio'}
                    </h1>
                    <p className="text-gray-500">
                        {isEditing
                            ? `Modificando registro ID: ${formData.customerId || 'N/A'}`
                            : 'Complete el formulario para dar de alta un nuevo socio.'}
                    </p>
                </div>

                <div className="flex gap-2">
                    <Button variant="secondary" onClick={handleExport}>
                        <Download className="mr-2 h-4 w-4" /> Exportar Excel
                    </Button>
                    <Button variant="secondary" onClick={handleBulkUpdateEmails} disabled={bulkUpdating}>
                        <RefreshCw className={`mr-2 h-4 w-4 ${bulkUpdating ? 'animate-spin' : ''}`} />
                        {bulkUpdating ? 'Actualizando...' : 'Actualizar Correos'}
                    </Button>
                    <div className="relative" ref={dropdownRef}>
                        <Button variant="secondary" onClick={() => { setShowDropdown(v => !v); fetchResetRequests(); }} className="relative">
                            <Bell className="mr-2 h-4 w-4" />
                            Solicitudes
                            {pendingCount > 0 && (
                                <span className="absolute -top-1.5 -right-1.5 bg-red-500 text-white text-[10px] font-bold w-5 h-5 rounded-full flex items-center justify-center animate-pulse">
                                    {pendingCount}
                                </span>
                            )}
                        </Button>
                        {showDropdown && (
                            <div className="absolute right-0 top-full mt-2 w-96 bg-white rounded-xl shadow-xl border border-gray-200 z-50 overflow-hidden">
                                <div className="flex items-center justify-between px-4 py-3 bg-amber-50 border-b border-amber-100">
                                    <span className="flex items-center gap-2 text-sm font-semibold text-amber-800">
                                        <Bell className="w-4 h-4" />
                                        Solicitudes Pendientes
                                        {pendingCount > 0 && (
                                            <span className="bg-red-500 text-white text-[10px] font-bold px-1.5 py-0.5 rounded-full">{pendingCount}</span>
                                        )}
                                    </span>
                                    <button onClick={() => setShowDropdown(false)} className="text-gray-400 hover:text-gray-600">
                                        <X className="w-4 h-4" />
                                    </button>
                                </div>
                                <div className="max-h-80 overflow-y-auto">
                                    {loadingRequests ? (
                                        <p className="px-4 py-6 text-sm text-center text-gray-400">Cargando...</p>
                                    ) : resetRequests.length === 0 ? (
                                        <div className="px-4 py-8 text-center">
                                            <CheckCircle className="w-8 h-8 text-green-400 mx-auto mb-2" />
                                            <p className="text-sm text-gray-500">Sin solicitudes pendientes</p>
                                        </div>
                                    ) : (
                                        <div className="divide-y divide-gray-100">
                                            {resetRequests.map(r => (
                                                <div key={r.id} className="px-4 py-3 hover:bg-gray-50">
                                                    <div className="flex items-start justify-between gap-2">
                                                        <div className="min-w-0">
                                                            <p className="text-sm font-semibold text-gray-800 truncate">{r.nombre || '—'}</p>
                                                            <p className="text-xs text-gray-500">{r.cedula || ''} {r.email ? `· ${r.email}` : ''}</p>
                                                            <p className="text-[11px] text-gray-400 mt-0.5">
                                                                {r.createdAt ? new Date(r.createdAt).toLocaleString('es-CO') : ''}
                                                            </p>
                                                        </div>
                                                        <div className="flex flex-col gap-1.5 shrink-0">
                                                            <button
                                                                onClick={() => handleResolveRequest(r.clientId, r.nombre)}
                                                                className="flex items-center gap-1 text-[11px] bg-green-700 hover:bg-green-600 text-white px-2 py-1 rounded-md whitespace-nowrap"
                                                            >
                                                                <KeyRound className="w-3 h-3" />
                                                                Resetear (Coop2025)
                                                            </button>
                                                            <button
                                                                onClick={() => handleRejectRequest(r.id, r.nombre)}
                                                                className="flex items-center gap-1 text-[11px] bg-red-600 hover:bg-red-500 text-white px-2 py-1 rounded-md whitespace-nowrap"
                                                            >
                                                                <XCircle className="w-3 h-3" />
                                                                Rechazar
                                                            </button>
                                                        </div>
                                                    </div>
                                                </div>
                                            ))}
                                        </div>
                                    )}
                                </div>
                            </div>
                        )}
                    </div>
                </div>
            </div>

            {/* Search Box */}
            <div className="flex justify-end mb-4">
                <form onSubmit={handleSearch} className="flex gap-2 w-full md:w-auto">
                    <div className="relative flex-1 md:w-64">
                        <Search className="absolute left-2.5 top-2.5 h-4 w-4 text-gray-400" />
                        <input
                            type="text"
                            aria-label="Buscar socio por cédula"
                            placeholder="Buscar por Cédula..."
                            className="w-full pl-9 pr-4 py-2 text-sm border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-brand-primary/50"
                            value={searchCedula}
                            onChange={(e) => setSearchCedula(e.target.value)}
                        />
                    </div>
                    <Button type="submit" variant="secondary" disabled={isSearching || !searchCedula}>
                        {isSearching ? '...' : 'Buscar'}
                    </Button>
                </form>
            </div>

            {/* Main Form Card */}
            <Card>
                <CardContent className="p-6">
                    <form onSubmit={handleSubmit} className="space-y-6">

                        {/* Status Banner when Editing */}
                        {isEditing && (
                            <div className="bg-blue-50 border border-blue-200 rounded-md p-3 flex items-center justify-between">
                                <div className="flex items-center gap-2 text-blue-700">
                                    <AlertCircle className="h-5 w-5" />
                                    <span className="font-medium">Modo Edición Activado</span>
                                </div>
                                <Button size="sm" variant="ghost" onClick={handleReset} type="button">
                                    <X className="h-4 w-4 mr-1" />
                                    Cancelar / Nuevo
                                </Button>
                            </div>
                        )}

                        {/* Sección 1: Identificación */}
                        <div className="space-y-4">
                            <h3 className="text-sm font-semibold text-brand-primary uppercase tracking-wider border-b border-gray-100 pb-1">Identificación</h3>
                            <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                                <FormField label="Customer ID (Auto-gen.)">
                                    <Input
                                        value={formData.customerId}
                                        onChange={(e) => setFormData({ ...formData, customerId: e.target.value })}
                                        disabled={!isEditing} // Auto-generated on create, editable on update if needed
                                        placeholder="(Automático)"
                                        className="font-mono font-bold text-brand-primary"
                                    />
                                </FormField>
                                <FormField label="Cédula *">
                                    <Input
                                        value={formData.cedula}
                                        onChange={(e) => setFormData({ ...formData, cedula: e.target.value })}
                                        required
                                        placeholder="Ej: 1234567890"
                                    />
                                </FormField>
                                <FormField label="Fecha Ingreso *">
                                    <Input
                                        type="date"
                                        value={formData.fechaIngreso}
                                        onChange={(e) => setFormData({ ...formData, fechaIngreso: e.target.value })}
                                        required
                                    />
                                </FormField>
                            </div>
                        </div>

                        {/* Sección 2: Datos Personales */}
                        <div className="space-y-4">
                            <h3 className="text-sm font-semibold text-brand-primary uppercase tracking-wider border-b border-gray-100 pb-1">Datos Personales</h3>
                            <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                                <FormField label="Nombres *">
                                    <Input
                                        value={formData.name}
                                        onChange={(e) => setFormData({ ...formData, name: e.target.value })}
                                        required
                                    />
                                </FormField>
                                <FormField label="Primer Apellido *">
                                    <Input
                                        value={formData.surname1}
                                        onChange={(e) => setFormData({ ...formData, surname1: e.target.value })}
                                        required
                                    />
                                </FormField>
                                <FormField label="Segundo Apellido">
                                    <Input
                                        value={formData.surname2}
                                        onChange={(e) => setFormData({ ...formData, surname2: e.target.value })}
                                    />
                                </FormField>
                            </div>
                            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                                <div className="space-y-2">
                                    <Label>Género</Label>
                                    <select
                                        aria-label="Género"
                                        className="flex h-10 w-full rounded-md border border-gray-300 bg-white px-3 py-2 text-sm focus:ring-2 focus:ring-brand-primary/20 focus:border-brand-primary outline-none"
                                        value={formData.genero}
                                        onChange={(e) => setFormData({ ...formData, genero: e.target.value })}
                                    >
                                        <option value="M">Masculino</option>
                                        <option value="F">Femenino</option>
                                        <option value="O">Otro</option>
                                    </select>
                                </div>
                                <FormField label="Correo Electrónico">
                                    <Input
                                        type="email"
                                        value={formData.email}
                                        onChange={(e) => {
                                            setEmailManuallySet(true);
                                            setFormData({ ...formData, email: e.target.value });
                                        }}
                                        placeholder="correo@credifuturo.com"
                                    />
                                    {!isEditing && !emailManuallySet && formData.email && (
                                        <p className="text-xs text-green-600 mt-1">Generado automáticamente</p>
                                    )}
                                </FormField>
                            </div>
                        </div>

                        {/* Sección 3: Ubicación y Perfil */}
                        <div className="space-y-4">
                            <h3 className="text-sm font-semibold text-brand-primary uppercase tracking-wider border-b border-gray-100 pb-1">Ubicación y Perfil</h3>
                            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                                <FormField label="País">
                                    <Input
                                        value={formData.pais}
                                        onChange={(e) => setFormData({ ...formData, pais: e.target.value })}
                                    />
                                </FormField>
                                <FormField label="Ciudad">
                                    <Input
                                        value={formData.ciudad}
                                        onChange={(e) => setFormData({ ...formData, ciudad: e.target.value })}
                                    />
                                </FormField>
                            </div>
                            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                                <div className="space-y-2">
                                    <Label>Socio Fundador</Label>
                                    <select
                                        aria-label="Socio Fundador"
                                        className="flex h-10 w-full rounded-md border border-gray-300 bg-white px-3 py-2 text-sm focus:ring-2 focus:ring-brand-primary/20 focus:border-brand-primary outline-none"
                                        value={formData.socioFundador}
                                        onChange={(e) => setFormData({ ...formData, socioFundador: e.target.value })}
                                    >
                                        <option value="SI">SI</option>
                                        <option value="NO">NO</option>
                                    </select>
                                </div>
                                <div className="space-y-2">
                                    <Label>Estatus</Label>
                                    <select
                                        aria-label="Estatus"
                                        className="flex h-10 w-full rounded-md border border-gray-300 bg-white px-3 py-2 text-sm focus:ring-2 focus:ring-brand-primary/20 focus:border-brand-primary outline-none"
                                        value={formData.estatus}
                                        onChange={(e) => setFormData({ ...formData, estatus: e.target.value })}
                                    >
                                        <option value="Activo">Activo</option>
                                        <option value="Inactivo">Inactivo</option>
                                    </select>
                                </div>
                            </div>
                            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                                <FormField label="Cargo">
                                    <Input
                                        value={formData.cargo}
                                        onChange={(e) => setFormData({ ...formData, cargo: e.target.value })}
                                    />
                                </FormField>
                                <FormField label="Referido Por">
                                    <Input
                                        value={formData.referido}
                                        onChange={(e) => setFormData({ ...formData, referido: e.target.value })}
                                    />
                                </FormField>
                            </div>
                        </div>

                        {/* Action Buttons */}
                        <div className="flex flex-col-reverse sm:flex-row justify-end gap-3 pt-6 border-t border-gray-200">

                            {isEditing && (
                                <>
                                <Button
                                    type="button"
                                    variant="destructive"
                                    onClick={handleDelete}
                                    disabled={loading}
                                    className="sm:mr-auto bg-red-50 text-red-600 hover:bg-red-100 hover:text-red-700 border-red-200"
                                >
                                    <Trash2 className="mr-2 h-4 w-4" />
                                    Eliminar Socio
                                </Button>
                                <Button
                                    type="button"
                                    variant="secondary"
                                    onClick={handleResetPassword}
                                    disabled={loading}
                                    className="bg-amber-50 text-amber-700 hover:bg-amber-100 border-amber-200"
                                >
                                    <KeyRound className="mr-2 h-4 w-4" />
                                    Resetear Contraseña
                                </Button>
                                </>
                            )}

                            <Button
                                type="button"
                                variant="ghost"
                                onClick={handleReset}
                                disabled={loading}
                            >
                                Limpiar / Cancelar
                            </Button>

                            <Button
                                type="submit"
                                size="lg"
                                disabled={loading}
                                className={isEditing ? "bg-amber-600 hover:bg-amber-700" : "bg-brand-primary hover:bg-brand-dark"}
                            >
                                <Save className="mr-2 h-4 w-4" />
                                {loading ? 'Procesando...' : (isEditing ? 'Actualizar Datos' : 'Registrar Socio')}
                            </Button>
                        </div>

                    </form>
                </CardContent>
            </Card>

        </div>
    );
};

export default ClientsPage;
