export const COLOMBIAN_BANKS = [
    'Bancolombia',
    'Banco de Bogotá',
    'Banco Davivienda',
    'Banco de Occidente',
    'BBVA Colombia',
    'Banco GNB Sudameris',
    'Banco Agrario de Colombia',
    'Citibank',
    'Banco Caja Social (BCSC)',
    'Scotiabank Colpatria',
    'Banco AV Villas',
    'Banco Popular',
    'Itáu Corpbanca Colombia',
    'Banco Pichincha',
    'Bancamía',
    'Banco Mundo Mujer',
    'Banco Unión',
    'Lulo Bank',
    'Banco W',
    'Banco Contactar',
    'Banco Falabella',
    'Banco BTG Pactual',
    'J.P. Morgan',
    'Banco Cooperativo Coopcentral',
    'Ban100',
    'Banco Santander',
    'Banco Serfinanza',
    'Mibanco Colombia',
    'Banco Finandina',
    'Bancoomeva',
    'Nequi',
    'Daviplata',
    'Dale',
    'Movii',
    'Nubank (NU)',
    'Ualá',
    'Rappipay',
    'Pibank'
].sort();

export const COLOMBIAN_BANKS_WITH_OTHER = [...COLOMBIAN_BANKS, 'Otro / No aplica'];
