import React, { useState, useEffect } from 'react';
import api from '../../config/api';
import { notifyUpdate } from '../../utils/sync';
import { Save, Search, Trash2, X, AlertCircle, CheckCircle, Download } from 'lucide-react';
import * as XLSX from 'xlsx';
import { Button } from '../../components/ui/Button';
import { Input, Label, FormField } from '../../components/ui/Input';
import { Card, CardHeader, CardTitle, CardContent } from '../../components/ui/Card';
import { useUi } from '../../context/UiContext';

const ClientsPage = () => {
    const { toast } = useUi();
    const [loading, setLoading] = useState(false);
    const [isEditing, setIsEditing] = useState(false);
    const [clients, setClients] = useState([]); // For export purposes

    // Search State
    const [searchCedula, setSearchCedula] = useState('');
    const [isSearching, setIsSearching] = useState(false);

    // Initial Form State
    const initialFormState = {
        id: '', // Database Primary Key
        customerId: '', // Business Key (Will be auto-generated by backend if empty)
        cedula: '',
        name: '',
        surname1: '',
        surname2: '',
        email: '',
        password: '123', // Default
        genero: 'M',
        pais: 'Colombia',
        ciudad: '',
        tipoCliente: 'Final',
        socioFundador: 'SI',
        referido: '',
        cargo: '',
        fechaIngreso: new Date().toISOString().split('T')[0],
        fechaBaja: '',
        estatus: 'Activo'
    };

    const [formData, setFormData] = useState(initialFormState);

    const fetchClients = async () => {
        try {
            const res = await api.get('/admin/clients');
            setClients(res.data);
        } catch (error) {
            console.error("Error fetching clients for export:", error);
        }
    };

    useEffect(() => {
        fetchClients();
    }, []);

    // --- Actions ---

    const handleSearch = async (e) => {
        e.preventDefault();
        if (!searchCedula.trim()) {
            toast.error('Ingrese una cédula para buscar.');
            return;
        }

        setIsSearching(true);
        try {
            // GET /clients/cedula/:cedula
            const res = await api.get(`/admin/clients/cedula/${searchCedula}`);
            const client = res.data;

            // Populate form with existing data
            setFormData({
                ...client,
                password: '', // Don't show hash
                surname1: client.surname1 || '',
                surname2: client.surname2 || '',
                referido: client.referido || '',
                cargo: client.cargo || '',
                ciudad: client.ciudad || '',
                fechaBaja: client.fechaBaja || ''
            });
            setIsEditing(true);
            toast.success('Socio encontrado. Modo edición activado.');
        } catch (error) {
            console.error("Search error:", error);
            if (error.response && error.response.status === 404) {
                toast.error('Socio no encontrado. Verifique la cédula.');
            } else {
                toast.error('Error en la búsqueda: ' + (error.message));
            }
            handleReset(); // Clean slate on error
        } finally {
            setIsSearching(false);
        }
    };

    const handleReset = () => {
        setFormData(initialFormState);
        setIsEditing(false);
        setSearchCedula('');
    };

    const handleSubmit = async (e) => {
        e.preventDefault();

        // Basic Frontend Validation
        if (!formData.cedula) return toast.error('La Cédula es obligatoria.');
        if (!formData.name) return toast.error('El Nombre es obligatorio.');
        if (!formData.surname1) return toast.error('El Primer Apellido es obligatorio.');

        setLoading(true);
        try {
            if (isEditing) {
                // UPDATE (PUT)
                await api.put(`/admin/clients/${formData.id}`, formData);
                toast.success('Socio actualizado exitosamente.');
            } else {
                // CREATE (POST)
                await api.post('/admin/clients', formData);
                toast.success('Socio registrado exitosamente.');
            }
            notifyUpdate('clients');
            handleReset();
        } catch (error) {
            console.error("Error saving client:", error);
            const msg = error.response?.data?.error || error.message;
            toast.error(`Error: ${msg}`);
        } finally {
            setLoading(false);
        }
    };

    const handleExport = () => {
        if (clients.length === 0) {
            toast.error('No hay datos para exportar.');
            return;
        }
        const dataToExport = clients.map(c => ({
            'Customer_id': c.customerId ?? '',
            'Nombre': c.name ?? '',
            '1 Apellido': c.surname1 ?? '',
            '2 Apellido': c.surname2 ?? '',
            'Estado': c.estatus ?? '',
            'Genero': c.genero ?? '',
            'Pais': c.pais ?? '',
            'Ciudad': c.ciudad ?? '',
            'Tipo de Cliente': c.tipoCliente ?? '',
            'Concatenar': [c.name, c.surname1, c.surname2].filter(Boolean).join(' '),
            'Socio Fundador': c.socioFundador ?? '',
            'Referido': c.referido ?? '',
            'Cargo': c.cargo ?? '',
            'Fecha de Ingreso': c.fechaIngreso ?? '',
            'Fecha de baja': c.fechaBaja ?? '',
            'Cedula': c.cedula ?? '',
            'Correo': c.email ?? '',
        }));

        const worksheet = XLSX.utils.json_to_sheet(dataToExport);
        const workbook = XLSX.utils.book_new();
        XLSX.utils.book_append_sheet(workbook, worksheet, 'Socios');
        XLSX.writeFile(workbook, 'Tabla_Clientes.xlsx');
        toast.success('Reporte de Socios descargado: Tabla_Clientes.xlsx');
    };

    const handleDelete = async () => {
        if (!formData.id) return;

        if (window.confirm(`¿Está seguro de eliminar al socio ${formData.name} ${formData.surname1}? Esta acción no se puede deshacer.`)) {
            setLoading(true);
            try {
                await api.delete(`/admin/clients/${formData.id}`);
                toast.success('Socio eliminado correctamente.');
                notifyUpdate('clients');
                handleReset();
                fetchClients(); // Refresh list
            } catch (error) {
                console.error("Delete error:", error);
                toast.error('Error al eliminar: ' + (error.message));
            } finally {
                setLoading(false);
            }
        }
    };

    return (
        <div className="max-w-4xl mx-auto space-y-6">

            {/* Header Area */}
            <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4 border-b border-gray-200 pb-4">
                <div>
                    <h1 className="text-2xl font-bold text-brand-dark">
                        {isEditing ? 'Editar Socio' : 'Registrar Nuevo Socio'}
                    </h1>
                    <p className="text-gray-500">
                        {isEditing
                            ? `Modificando registro ID: ${formData.customerId || 'N/A'}`
                            : 'Complete el formulario para dar de alta un nuevo socio.'}
                    </p>
                </div>

                <div className="flex gap-2">
                    <Button variant="secondary" onClick={handleExport}>
                        <Download className="mr-2 h-4 w-4" /> Exportar Excel
                    </Button>
                </div>
            </div>

            {/* Search Box */}
            <div className="flex justify-end mb-4">
                <form onSubmit={handleSearch} className="flex gap-2 w-full md:w-auto">
                    <div className="relative flex-1 md:w-64">
                        <Search className="absolute left-2.5 top-2.5 h-4 w-4 text-gray-400" />
                        <input
                            type="text"
                            placeholder="Buscar por Cédula..."
                            className="w-full pl-9 pr-4 py-2 text-sm border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-brand-primary/50"
                            value={searchCedula}
                            onChange={(e) => setSearchCedula(e.target.value)}
                        />
                    </div>
                    <Button type="submit" variant="secondary" disabled={isSearching || !searchCedula}>
                        {isSearching ? '...' : 'Buscar'}
                    </Button>
                </form>
            </div>

            {/* Main Form Card */}
            <Card>
                <CardContent className="p-6">
                    <form onSubmit={handleSubmit} className="space-y-6">

                        {/* Status Banner when Editing */}
                        {isEditing && (
                            <div className="bg-blue-50 border border-blue-200 rounded-md p-3 flex items-center justify-between">
                                <div className="flex items-center gap-2 text-blue-700">
                                    <AlertCircle className="h-5 w-5" />
                                    <span className="font-medium">Modo Edición Activado</span>
                                </div>
                                <Button size="sm" variant="ghost" onClick={handleReset} type="button">
                                    <X className="h-4 w-4 mr-1" />
                                    Cancelar / Nuevo
                                </Button>
                            </div>
                        )}

                        {/* Sección 1: Identificación */}
                        <div className="space-y-4">
                            <h3 className="text-sm font-semibold text-brand-primary uppercase tracking-wider border-b border-gray-100 pb-1">Identificación</h3>
                            <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                                <FormField label="Customer ID (Auto-gen.)">
                                    <Input
                                        value={formData.customerId}
                                        onChange={(e) => setFormData({ ...formData, customerId: e.target.value })}
                                        disabled={!isEditing} // Auto-generated on create, editable on update if needed
                                        placeholder="(Automático)"
                                        className="font-mono font-bold text-brand-primary"
                                    />
                                </FormField>
                                <FormField label="Cédula *">
                                    <Input
                                        value={formData.cedula}
                                        onChange={(e) => setFormData({ ...formData, cedula: e.target.value })}
                                        required
                                        placeholder="Ej: 1234567890"
                                    />
                                </FormField>
                                <FormField label="Fecha Ingreso *">
                                    <Input
                                        type="date"
                                        value={formData.fechaIngreso}
                                        onChange={(e) => setFormData({ ...formData, fechaIngreso: e.target.value })}
                                        required
                                    />
                                </FormField>
                            </div>
                        </div>

                        {/* Sección 2: Datos Personales */}
                        <div className="space-y-4">
                            <h3 className="text-sm font-semibold text-brand-primary uppercase tracking-wider border-b border-gray-100 pb-1">Datos Personales</h3>
                            <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                                <FormField label="Nombres *">
                                    <Input
                                        value={formData.name}
                                        onChange={(e) => setFormData({ ...formData, name: e.target.value })}
                                        required
                                    />
                                </FormField>
                                <FormField label="Primer Apellido *">
                                    <Input
                                        value={formData.surname1}
                                        onChange={(e) => setFormData({ ...formData, surname1: e.target.value })}
                                        required
                                    />
                                </FormField>
                                <FormField label="Segundo Apellido">
                                    <Input
                                        value={formData.surname2}
                                        onChange={(e) => setFormData({ ...formData, surname2: e.target.value })}
                                    />
                                </FormField>
                            </div>
                            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                                <div className="space-y-2">
                                    <Label>Género</Label>
                                    <select
                                        className="flex h-10 w-full rounded-md border border-gray-300 bg-white px-3 py-2 text-sm focus:ring-2 focus:ring-brand-primary/20 focus:border-brand-primary outline-none"
                                        value={formData.genero}
                                        onChange={(e) => setFormData({ ...formData, genero: e.target.value })}
                                    >
                                        <option value="M">Masculino</option>
                                        <option value="F">Femenino</option>
                                        <option value="O">Otro</option>
                                    </select>
                                </div>
                                <FormField label="Correo Electrónico (Opcional)">
                                    <Input
                                        type="email"
                                        value={formData.email}
                                        onChange={(e) => setFormData({ ...formData, email: e.target.value })}
                                        placeholder="correo@ejemplo.com"
                                    />
                                </FormField>
                            </div>
                        </div>

                        {/* Sección 3: Ubicación y Perfil */}
                        <div className="space-y-4">
                            <h3 className="text-sm font-semibold text-brand-primary uppercase tracking-wider border-b border-gray-100 pb-1">Ubicación y Perfil</h3>
                            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                                <FormField label="País">
                                    <Input
                                        value={formData.pais}
                                        onChange={(e) => setFormData({ ...formData, pais: e.target.value })}
                                    />
                                </FormField>
                                <FormField label="Ciudad">
                                    <Input
                                        value={formData.ciudad}
                                        onChange={(e) => setFormData({ ...formData, ciudad: e.target.value })}
                                    />
                                </FormField>
                            </div>
                            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                                <div className="space-y-2">
                                    <Label>Socio Fundador</Label>
                                    <select
                                        className="flex h-10 w-full rounded-md border border-gray-300 bg-white px-3 py-2 text-sm focus:ring-2 focus:ring-brand-primary/20 focus:border-brand-primary outline-none"
                                        value={formData.socioFundador}
                                        onChange={(e) => setFormData({ ...formData, socioFundador: e.target.value })}
                                    >
                                        <option value="SI">SI</option>
                                        <option value="NO">NO</option>
                                    </select>
                                </div>
                                <div className="space-y-2">
                                    <Label>Estatus</Label>
                                    <select
                                        className="flex h-10 w-full rounded-md border border-gray-300 bg-white px-3 py-2 text-sm focus:ring-2 focus:ring-brand-primary/20 focus:border-brand-primary outline-none"
                                        value={formData.estatus}
                                        onChange={(e) => setFormData({ ...formData, estatus: e.target.value })}
                                    >
                                        <option value="Activo">Activo</option>
                                        <option value="Inactivo">Inactivo</option>
                                    </select>
                                </div>
                            </div>
                            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                                <FormField label="Cargo">
                                    <Input
                                        value={formData.cargo}
                                        onChange={(e) => setFormData({ ...formData, cargo: e.target.value })}
                                    />
                                </FormField>
                                <FormField label="Referido Por">
                                    <Input
                                        value={formData.referido}
                                        onChange={(e) => setFormData({ ...formData, referido: e.target.value })}
                                    />
                                </FormField>
                            </div>
                        </div>

                        {/* Action Buttons */}
                        <div className="flex flex-col-reverse sm:flex-row justify-end gap-3 pt-6 border-t border-gray-200">

                            {isEditing && (
                                <Button
                                    type="button"
                                    variant="destructive"
                                    onClick={handleDelete}
                                    disabled={loading}
                                    className="sm:mr-auto bg-red-50 text-red-600 hover:bg-red-100 hover:text-red-700 border-red-200"
                                >
                                    <Trash2 className="mr-2 h-4 w-4" />
                                    Eliminar Socio
                                </Button>
                            )}

                            <Button
                                type="button"
                                variant="ghost"
                                onClick={handleReset}
                                disabled={loading}
                            >
                                Limpiar / Cancelar
                            </Button>

                            <Button
                                type="submit"
                                size="lg"
                                disabled={loading}
                                className={isEditing ? "bg-amber-600 hover:bg-amber-700" : "bg-brand-primary hover:bg-brand-dark"}
                            >
                                <Save className="mr-2 h-4 w-4" />
                                {loading ? 'Procesando...' : (isEditing ? 'Actualizar Datos' : 'Registrar Socio')}
                            </Button>
                        </div>

                    </form>
                </CardContent>
            </Card>
        </div>
    );
};

export default ClientsPage;
